#
# Module manifest for module 'DnsRecordTools'
#
# Generated by: kannis.wong
#
# Generated on: 2/14/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule          = 'DnsRecordTools.psm1'
ModuleVersion       = '1.0.0'
GUID                = '4dacdfce-399c-4bbc-8489-d074a5dd874d'
Author              = 'kannis.wong'
Copyright           = '(c) Kannis.Wong. All rights reserved.'
Description         = 'Normalize Get-DnsServerResourceRecord output into a consistent object schema for filtering, exporting, and comparison.'
PowerShellVersion   = '5.1'

FunctionsToExport   = @(
    'ConvertFrom-DnsRecord'
)

CmdletsToExport     = @()
VariablesToExport   = '*'
AliasesToExport     = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'DNS',
            'WindowsDNS',
            'DnsServer',
            'ConvertDNS',
            'Get-DnsServerResourceRecord',
            'System',
            'Management',
            'Configuration'
        )
        # A URL to the license for this module.
        LicenseUri = 'https://github.com/Kannis-Wong/DnsRecordTools'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Kannis-Wong/DnsRecordTools'

    }
}

HelpInfoURI = 'https://github.com/Kannis-Wong/DnsRecordTools'

}
